package com.example.WeatherReport.Utils;


import android.content.Context;
import android.os.Environment;

import java.util.ArrayList;
import java.util.List;
import java.util.Locale;

public class Utils {
    public static String SRV_URL = "http://api.accuweather.com";
    public static String SRV_VER = "v1";
    public static String SRV_KEY = "296894b065a2471290a6750ff2dbd619"; //Lenovo ApiKey :)
    public static String DB_NAME_KEY = "report_weather.db";
    public static String getLanguage(Context context) {

        Locale locale;
        String lCountry, lLanguage, retLanguage = "en";
        List<String> languageArray = new ArrayList<>();

        locale = context.getResources().getConfiguration().locale;
        lCountry = locale.getCountry();
        lLanguage = locale.getLanguage();

        languageArray.add("ar");
        languageArray.add("ar-dz");
        languageArray.add("ar-bh");
        languageArray.add("ar-eg");
        languageArray.add("ar-iq");
        languageArray.add("ar-jo");
        languageArray.add("ar-kw");
        languageArray.add("ar-lb");
        languageArray.add("ar-ly");
        languageArray.add("ar-ma");
        languageArray.add("ar-om");
        languageArray.add("ar-qa");
        languageArray.add("ar-sa");
        languageArray.add("ar-sd");
        languageArray.add("ar-sy");
        languageArray.add("ar-tn");
        languageArray.add("ar-ae");
        languageArray.add("ar-ye");
        languageArray.add("az");
        languageArray.add("az-latn");
        languageArray.add("az-latn-az");
        languageArray.add("bn");
        languageArray.add("bn-bd");
        languageArray.add("bn-in");
        languageArray.add("bs");
        languageArray.add("bs-ba");
        languageArray.add("bg");
        languageArray.add("bg-bg");
        languageArray.add("ca");
        languageArray.add("ca-es");
        languageArray.add("zh");
        languageArray.add("zh-hk");
        languageArray.add("zh-mo");
        languageArray.add("zh-cn");
        languageArray.add("zh-hans");
        languageArray.add("zh-hans-cn");
        languageArray.add("zh-hans-hk");
        languageArray.add("zh-hans-mo");
        languageArray.add("zh-hans-sg");
        languageArray.add("zh-sg");
        languageArray.add("zh-tw");
        languageArray.add("zh-hant");
        languageArray.add("zh-hant-hk");
        languageArray.add("zh-hant-mo");
        languageArray.add("zh-hant-tw");
        languageArray.add("hr");
        languageArray.add("hr-hr");
        languageArray.add("cs");
        languageArray.add("cs-cz");
        languageArray.add("da");
        languageArray.add("da-dk");
        languageArray.add("nl");
        languageArray.add("nl-aw");
        languageArray.add("nl-be");
        languageArray.add("nl-cw");
        languageArray.add("nl-nl");
        languageArray.add("nl-sx");
        languageArray.add("en");
        languageArray.add("en-as");
        languageArray.add("en-au");
        languageArray.add("en-bb");
        languageArray.add("en-be");
        languageArray.add("en-bz");
        languageArray.add("en-bm");
        languageArray.add("en-bw");
        languageArray.add("en-cm");
        languageArray.add("en-ca");
        languageArray.add("en-gh");
        languageArray.add("en-gu");
        languageArray.add("en-gy");
        languageArray.add("en-hk");
        languageArray.add("en-in");
        languageArray.add("en-ie");
        languageArray.add("en-jm");
        languageArray.add("en-ke");
        languageArray.add("en-mw");
        languageArray.add("en-my");
        languageArray.add("en-mt");
        languageArray.add("en-mh");
        languageArray.add("en-mu");
        languageArray.add("en-na");
        languageArray.add("en-nz");
        languageArray.add("en-ng");
        languageArray.add("en-mp");
        languageArray.add("en-pk");
        languageArray.add("en-ph");
        languageArray.add("en-rw");
        languageArray.add("en-sg");
        languageArray.add("en-za");
        languageArray.add("en-tz");
        languageArray.add("en-th");
        languageArray.add("en-tt");
        languageArray.add("en-um");
        languageArray.add("en-vi");
        languageArray.add("en-ug");
        languageArray.add("en-gb");
        languageArray.add("en-us");
        languageArray.add("en-zm");
        languageArray.add("en-zw");
        languageArray.add("et");
        languageArray.add("et-ee");
        languageArray.add("fa");
        languageArray.add("fa-af");
        languageArray.add("fa-ir");
        languageArray.add("fil");
        languageArray.add("fil-ph");
        languageArray.add("fi");
        languageArray.add("fi-fi");
        languageArray.add("fr");
        languageArray.add("fr-dz");
        languageArray.add("fr-be");
        languageArray.add("fr-bj");
        languageArray.add("fr-bf");
        languageArray.add("fr-bi");
        languageArray.add("fr-cm");
        languageArray.add("fr-ca");
        languageArray.add("fr-cf");
        languageArray.add("fr-td");
        languageArray.add("fr-km");
        languageArray.add("fr-cg");
        languageArray.add("fr-cd");
        languageArray.add("fr-ci");
        languageArray.add("fr-dj");
        languageArray.add("fr-gq");
        languageArray.add("fr-fr");
        languageArray.add("fr-gf");
        languageArray.add("fr-ga");
        languageArray.add("fr-gp");
        languageArray.add("fr-gn");
        languageArray.add("fr-lu");
        languageArray.add("fr-mg");
        languageArray.add("fr-ml");
        languageArray.add("fr-mq");
        languageArray.add("fr-mu");
        languageArray.add("fr-yt");
        languageArray.add("fr-mc");
        languageArray.add("fr-ma");
        languageArray.add("fr-ne");
        languageArray.add("fr-re");
        languageArray.add("fr-rw");
        languageArray.add("fr-bl");
        languageArray.add("fr-mf");
        languageArray.add("fr-sn");
        languageArray.add("fr-sc");
        languageArray.add("fr-ch");
        languageArray.add("fr-tg");
        languageArray.add("fr-tn");
        languageArray.add("de");
        languageArray.add("de-at");
        languageArray.add("de-be");
        languageArray.add("de-de");
        languageArray.add("de-li");
        languageArray.add("de-lu");
        languageArray.add("de-ch");
        languageArray.add("el");
        languageArray.add("el-cy");
        languageArray.add("el-gr");
        languageArray.add("gu");
        languageArray.add("he");
        languageArray.add("he-il");
        languageArray.add("hi");
        languageArray.add("hi-in");
        languageArray.add("hu");
        languageArray.add("hu-hu");
        languageArray.add("is");
        languageArray.add("is-is");
        languageArray.add("id");
        languageArray.add("id-id");
        languageArray.add("it");
        languageArray.add("it-it");
        languageArray.add("it-ch");
        languageArray.add("ja");
        languageArray.add("ja-jp");
        languageArray.add("kn");
        languageArray.add("kk");
        languageArray.add("kk-kz");
        languageArray.add("ko");
        languageArray.add("ko-kr");
        languageArray.add("lv");
        languageArray.add("lv-lv");
        languageArray.add("lt");
        languageArray.add("lt-lt");
        languageArray.add("mk");
        languageArray.add("mk-mk");
        languageArray.add("ms");
        languageArray.add("ms-bn");
        languageArray.add("ms-my");
        languageArray.add("mr");
        languageArray.add("sr-me");
        languageArray.add("nb");
        languageArray.add("pl");
        languageArray.add("pl-pl");
        languageArray.add("pt");
        languageArray.add("pt-ao");
        languageArray.add("pt-br");
        languageArray.add("pt-cv");
        languageArray.add("pt-gw");
        languageArray.add("pt-mz");
        languageArray.add("pt-pt");
        languageArray.add("pt-st");
        languageArray.add("pa");
        languageArray.add("pa-in");
        languageArray.add("ro");
        languageArray.add("ro-md");
        languageArray.add("ro-mo");
        languageArray.add("ro-ro");
        languageArray.add("ru");
        languageArray.add("ru-md");
        languageArray.add("ru-mo");
        languageArray.add("ru-ru");
        languageArray.add("ru-ua");
        languageArray.add("sr");
        languageArray.add("sr-latn");
        languageArray.add("sr-latn-ba");
        languageArray.add("sr-me");
        languageArray.add("sr-rs");
        languageArray.add("sk");
        languageArray.add("sk-sk");
        languageArray.add("sl");
        languageArray.add("sl-sl");
        languageArray.add("es");
        languageArray.add("es-ar");
        languageArray.add("es-bo");
        languageArray.add("es-cl");
        languageArray.add("es-co");
        languageArray.add("es-cr");
        languageArray.add("es-do");
        languageArray.add("es-ec");
        languageArray.add("es-sv");
        languageArray.add("es-gq");
        languageArray.add("es-gt");
        languageArray.add("es-hn");
        languageArray.add("es-419");
        languageArray.add("es-mx");
        languageArray.add("es-ni");
        languageArray.add("es-pa");
        languageArray.add("es-py");
        languageArray.add("es-pu");
        languageArray.add("es-pr");
        languageArray.add("es-es");
        languageArray.add("es-us");
        languageArray.add("es-uy");
        languageArray.add("es-ve");
        languageArray.add("sw");
        languageArray.add("sw-cd");
        languageArray.add("sw-ke");
        languageArray.add("sw-tz");
        languageArray.add("sw-ug");
        languageArray.add("sv");
        languageArray.add("sv-fi");
        languageArray.add("sv-se");
        languageArray.add("tl");
        languageArray.add("ta");
        languageArray.add("ta-in");
        languageArray.add("ta-lk");
        languageArray.add("te");
        languageArray.add("te-in");
        languageArray.add("th");
        languageArray.add("th-th");
        languageArray.add("tr");
        languageArray.add("tr-tr");
        languageArray.add("uk");
        languageArray.add("uk-ua");
        languageArray.add("ur");
        languageArray.add("ur-bd");
        languageArray.add("ur-in");
        languageArray.add("ur-np");
        languageArray.add("ur-pk");
        languageArray.add("uz");
        languageArray.add("uz-latn");
        languageArray.add("uz-latn-uz");
        languageArray.add("vi");
        languageArray.add("vi-vn");

        if (lCountry.length() > 0 && lLanguage.length() > 0 && !lLanguage.toLowerCase().equals(lCountry.toLowerCase()) && languageArray.contains(lCountry.toLowerCase() + "-" + lLanguage.toLowerCase()))
            retLanguage = lCountry.toLowerCase() + "-" + lLanguage.toLowerCase();
        else if (lCountry.length() > 0 && languageArray.contains(lCountry))
            retLanguage = lCountry.toLowerCase();
        else if (lLanguage.length() > 0 && languageArray.contains(lLanguage))
            retLanguage = lLanguage.toLowerCase();

        return retLanguage;
    }

}
